In [1]:
import numpy as np

In [5]:
#Q1
print(np.add(2.0, 74.0))
print(np.subtract(55.5, 9.3))
print(np.multiply(4.3, 6.6))
print(np.divide(478, 65))

76.0
46.2
28.38
7.3538461538461535


In [11]:
#q2 - round elements in an array

test_array = np.random.rand(1, 10)
print(test_array)

nearestint_test_array = np.rint(test_array)
print(nearestint_test_array)

[[0.64511047 0.56676045 0.0902557  0.69389123 0.7668822  0.90413014
  0.04377607 0.35684652 0.65303717 0.14422823]]
[[1. 1. 0. 1. 1. 1. 0. 0. 1. 0.]]


In [13]:
#Q3 - get the true division of the element-wise array inputs
new_array = np.random.randint(15, size=10)
print(new_array)
divided_new_array = np.true_divide(new_array, 4)
print(divided_new_array)

[ 9  8  5  4  3  3  1  9  0 11]
[2.25 2.   1.25 1.   0.75 0.75 0.25 2.25 0.   2.75]


In [16]:
#Extension Q1
array_one = np.random.rand(5,3)
print('Array one')
print(array_one)
array_two = np.random.rand(3,2)
print('Array two')
print(array_two)
real_matrix_product = np.dot(array_one, array_two)
print('Real matrix product')
print(real_matrix_product)

Array one
[[0.86051462 0.66090218 0.74376549]
 [0.79920425 0.07194923 0.82141077]
 [0.71185467 0.99585512 0.99166823]
 [0.05409942 0.24874236 0.0406866 ]
 [0.01719166 0.45215173 0.80614055]]
Array two
[[0.63408506 0.13109551]
 [0.25671665 0.39619834]
 [0.70275116 0.1441128 ]]
Real matrix product
[[1.23798611 0.48184407]
 [1.10248141 0.25165406]
 [1.403925   0.63078917]
 [0.1267525  0.11150696]
 [0.69349205 0.29757068]]


In [20]:
#Extension Q2
array_1000_element = np.random.randint(500, size=1000)
print('Avergae:')
mean_of_array = array_1000_element.mean()
print(mean_of_array)
print('Standard Deviation:')
std_of_array = array_1000_element.std()
print(std_of_array)
print('Variance:')
variance_of_array = array_1000_element.var()
print(variance_of_array)

Avergae:
246.912
Standard Deviation:
146.2896040598921
Variance:
21400.648255999997


In [22]:
#Extension Q3
an_array = np.array([12.9, 34.6, 11.5, 2.4, 4.6, 52.1])
print(an_array)
print('Round:')
rounded_arrary = np.around(an_array)
print(rounded_arrary)
print('Floor:')
floor_array = np.floor(an_array)
print(floor_array)
print('Ceil:')
ceil_array = np.ceil(an_array)
print(ceil_array)
print('Trunc:')
trunc_array = np.trunc(an_array)
print(trunc_array)
print('Round Input')
round_input_array = [round(input) for input in an_array]
print(round_input_array)


[12.9 34.6 11.5  2.4  4.6 52.1]
Round:
[13. 35. 12.  2.  5. 52.]
Floor:
[12. 34. 11.  2.  4. 52.]
Ceil:
[13. 35. 12.  3.  5. 53.]
Trunc:
[12. 34. 11.  2.  4. 52.]
Round Input
[13, 35, 12, 2, 5, 52]


In [23]:
#Extension Q$
final_array = np.random.randint(1000, size=10)
print(final_array)
print('Max Element')
max_element = np.amax(final_array)
print(max_element)
print('Min Element')
min_element = np.amin(final_array)
print(min_element)


[484 667 227 927 679 467 530 823 927 951]
Max Element
951
Min Element
227
