In [2]:
import numpy as np


In [5]:
array1D = np.array ([1,2,3,4,5,6,7,8,9])

array2D = np.array ([[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9]])

print(array1D.ndim)
print(array2D.ndim)

1
2


In [9]:
array30_to_70 = np.arange(30, 71)

print(array30_to_70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [10]:
array1D = np.append(array1D, 10)

print(array1D)

[ 1  2  3  4  5  6  7  8  9 10 10]


In [12]:
print(np.shape(array2D))

(2, 9)


In [14]:
array30_to_70_even = np.arange(30, 71, 2)
print(array30_to_70_even)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [4]:
test_list = [1,4,6,7,1]
test_tuple = (1, 3, 4, 5, 6)

list_to_array = np.array(test_list)
tuple_to_array = np.asarray(test_tuple)

print(list_to_array)
print(tuple_to_array)
print(type(list_to_array))
print(type(tuple_to_array))

[1 4 6 7 1]
[1 3 4 5 6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
#This question did not provide the required information to complete it. I found this information
#on w3resource were the question was taken from.

data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))    

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]
