In [1]:
import numpy as np

In [5]:
#Q1
print(np.add(2.0, 74.0))
print(np.subtract(55.5, 9.3))
print(np.multiply(4.3, 6.6))
print(np.divide(478, 65))

76.0
46.2
28.38
7.3538461538461535


In [11]:
#q2 - round elements in an array

test_array = np.random.rand(1, 10)
print(test_array)

nearestint_test_array = np.rint(test_array)
print(nearestint_test_array)

[[0.64511047 0.56676045 0.0902557  0.69389123 0.7668822  0.90413014
  0.04377607 0.35684652 0.65303717 0.14422823]]
[[1. 1. 0. 1. 1. 1. 0. 0. 1. 0.]]


In [13]:
#Q3 - get the true division of the element-wise array inputs
new_array = np.random.randint(15, size=10)
print(new_array)
divided_new_array = np.true_divide(new_array, 4)
print(divided_new_array)

[ 9  8  5  4  3  3  1  9  0 11]
[2.25 2.   1.25 1.   0.75 0.75 0.25 2.25 0.   2.75]
